apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.wearbridge'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "expo.modules.wearbridge"
  compileSdkVersion safeExtGet("compileSdkVersion", 36)
  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 36)
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.google.android.gms:play-services-wearable:19.0.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0"
}
